[CALCITE-6559] Query with measure that applies AVG to SMALLINT throws AssertionError "Cannot add expression of different type to set"
When a query has a measure that is AVG applied to a SMALLINT or TINYINT
column, we get the following assertion failure:

  java.lang.AssertionError: Cannot add expression of different type to set:
  set type is RecordType(VARCHAR(9) JOB, MEASURE<SMALLINT NOT NULL> NOT NULL $f1, SMALLINT $f0) NOT NULL
  expression type is RecordType(VARCHAR(9) JOB, MEASURE<SMALLINT NOT NULL> NOT NULL $f1, SMALLINT NOT NULL $f0) NOT NULL

The problem is that a cast is added internally to the result of
SUM / COUNT, but this cast prevents a cast to nullable for the
null-generating side of the outer join. (The outer join comes from
the expansion of the measure as a correlated scalar subquery.)

Add method RexBuilder.makeNullable, sharing implementation with
existing method makeNotNull.

Add tests to scalar.iq and lateral.iq for some tricky query patterns
that already work.

Close apache/calcite#3950